### ISSUE TITLE
[BUG] Authentication required for Account. (421)

### ISSUE THREAD

**Issue by SRK7Kyros** [mandarons/icloudpy#19]
**Describe the bug**
I make an ICloudPyService instance and try to access any API then it prints out the error.

**To Reproduce**
1. Make an ICloudPyService instance
2. run ```api.drive.dir()```

Edit 1:
**Expected Behaviour**
The program returns a list containing all the folders that are present on iCloud root

**Screenshots**
Not applicable I think (correct me if im wrong), would just paste in the error, but it's already in the title.

**Configuration**
I'm not sure about this one, but here are my versions if that's what is asked:
Windows: 64 Bit, 21H2
Python: 3.9.12
ICloudPy: 0.3.3

**Additional context**
No additional context.

**Comment by mandarons** [comment]
Please fill in missing required information:

Expected behavior A clear and concise description of what you expected to happen.

Screenshots If applicable, add screenshots to help explain your problem.

Configuration If applicable, please share the configuration details

Additional context Add any other context about the problem here.

**Comment by SRK7Kyros** [comment]
> Please fill in missing required information:
> 
> Expected behavior A clear and concise description of what you expected to happen.
> 
> Screenshots If applicable, add screenshots to help explain your problem.
> 
> Configuration If applicable, please share the configuration details
> 
> Additional context Add any other context about the problem here.

done

**Comment by mandarons** [comment]
What's the error message?
